[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.5",
    "langchain>=0.3.23",
    "langchain-google-genai>=2.0.10",
    "streamlit>=1.44.1",
]
